[package]
name = "todo-app"
version = "0.1.0"
author = ["usagrada"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
wasm-logger = "0.2.0"
yew = "0.19"
yew-router = "0.16"
